name: digital_mental_health_app
description: “Digital Mental Health and Psychological Support System for Students in Higher Education.”
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  go_router: ^16.2.1
  dio: ^5.9.0
  freezed_annotation: ^3.1.0       # upgraded
  json_annotation: ^4.9.0          # upgraded
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2                    # upgraded
  cached_network_image: ^3.4.1     # upgraded
  flutter_chat_ui: ^2.9.0

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  firebase_analytics: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.2.0                  # upgraded
  build_runner: ^2.7.0             # upgraded
  json_serializable: ^6.11.0       # upgraded
  flutter_lints: ^6.0.0            # upgraded

flutter:
  uses-material-design: true
