// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBjqoeE8eyziMKD2b_P7R73uUsItysZOw',
    appId: '1:588081979285:web:4257e8c9aea0a9da4f209c',
    messagingSenderId: '588081979285',
    projectId: 'mentalhealthapp-a3a5b',
    authDomain: 'mentalhealthapp-a3a5b.firebaseapp.com',
    storageBucket: 'mentalhealthapp-a3a5b.firebasestorage.app',
    measurementId: 'G-YTRFC5Q5WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZh8MaYdczzhWVXUaUAqf9c2cqishSk0',
    appId: '1:588081979285:android:35d8122af7d233824f209c',
    messagingSenderId: '588081979285',
    projectId: 'mentalhealthapp-a3a5b',
    storageBucket: 'mentalhealthapp-a3a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nI4IZFE3OPITZqNuzzRySG0BxklpbgM',
    appId: '1:588081979285:ios:384fea02938e3c824f209c',
    messagingSenderId: '588081979285',
    projectId: 'mentalhealthapp-a3a5b',
    storageBucket: 'mentalhealthapp-a3a5b.firebasestorage.app',
    iosBundleId: 'com.mhapp.digitalMentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-nI4IZFE3OPITZqNuzzRySG0BxklpbgM',
    appId: '1:588081979285:ios:384fea02938e3c824f209c',
    messagingSenderId: '588081979285',
    projectId: 'mentalhealthapp-a3a5b',
    storageBucket: 'mentalhealthapp-a3a5b.firebasestorage.app',
    iosBundleId: 'com.mhapp.digitalMentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBjqoeE8eyziMKD2b_P7R73uUsItysZOw',
    appId: '1:588081979285:web:287d0df512d265bc4f209c',
    messagingSenderId: '588081979285',
    projectId: 'mentalhealthapp-a3a5b',
    authDomain: 'mentalhealthapp-a3a5b.firebaseapp.com',
    storageBucket: 'mentalhealthapp-a3a5b.firebasestorage.app',
    measurementId: 'G-QP9P50FJNL',
  );
}
